# This file was generated by GoReleaser. DO NOT EDIT.
cask "equipr" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "05e77f0a692e0b89ac0d1aec140ec8caaa9f78694b33e3c63803b32069152137"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "ab118c0ddc8fcc5ee16f09ede236babfc4a075be155ff407a5770a21d9b17b96"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ce7bb92a0c2e0f5eb4b83f6a9d9b225fdc46acfca3b678ced1f1a3ea6c7fba22"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "5409dfa592c4bf459f2de5d7bb3ced5bfe9446cb02c17f3222dcac8ecf5daa0a"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-arm64.tar.gz"
    end
  end

  name "equipr"
  desc "Equip your coding agents with skills, commands, and MCP servers"
  homepage "https://github.com/maquina-app/equipr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equipr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equipr"]
    end
  end

  # No zap stanza required

end
