# This file was generated by GoReleaser. DO NOT EDIT.
cask "equipr" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "a9ca022ab85d698c657ef41855dc83cd876cf8e26bef586fc1831be4ed54c98a"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "8084b228dea587f37d111961e150bb978c64af3d80415f2f016d556d1a4cf867"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5127036ff5077a8c30beff20f0b44488031e83696d7189e87dbb1878c2c232d9"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "52dd6d1cc63fadc6a90c3922f6f89fa9a7af54cbe3d3cae3adb1db58a629814a"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-arm64.tar.gz"
    end
  end

  name "equipr"
  desc "Equip your coding agents with skills, commands, and MCP servers"
  homepage "https://github.com/maquina-app/equipr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equipr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equipr"]
    end
  end

  # No zap stanza required

end
