# This file was generated by GoReleaser. DO NOT EDIT.
cask "equipr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a083fad7a7bbf164eeafd30d1b722449da1ec326b673e08f970693d58050c621"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "447864f036572ddf62d791ef4821ea41593c392a7a759911ed5bc66145db61d8"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e3bc8c5069643233dfe5f72885cd515c5cce96ea17c580a88bf7e20d74eb8f50"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "4612b3305fc91de88c0404e26e3748eb40ee0bc9e319dcfc33f260a808597526"
      url "https://github.com/maquina-app/equipr/releases/download/v#{version}/equipr-linux-arm64.tar.gz"
    end
  end

  name "equipr"
  desc "Equip your coding agents with skills, commands, and MCP servers"
  homepage "https://github.com/maquina-app/equipr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "equipr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/equipr"]
    end
  end

  # No zap stanza required

end
