# This file was generated by GoReleaser. DO NOT EDIT.
cask "fragua" do
  version "1.16.0"

  on_macos do
    on_intel do
      sha256 "4f6c5d00ab4787982b9dbddd12c01a059064eb20713fa30a56d905fa62e4cbab"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "a0bdd9164827c685edd2aa44eac974df2a2aea19b1defaebee5d76d3c163e48b"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ae982f6834baf2d8e2ab5daad7f291d3b71fed9bcc1a1719f1d9520037821936"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "005490c7ced4cf5a41f1efa6b4609af415b200e38b142b4b5a5ffeb28298c3c5"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-arm64.tar.gz"
    end
  end

  name "fragua"
  desc "Fragua execution host — run Fragua agents on your own machine"
  homepage "https://fragua.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fragua"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fragua"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next steps:
      fragua login          # store your AgentToken
      fragua agent install  # run the daemon at login (launchd LaunchAgent)
  EOS
end
