# This file was generated by GoReleaser. DO NOT EDIT.
cask "fragua" do
  version "1.8.1"

  on_macos do
    on_intel do
      sha256 "97b77367f5bfc779c16ed944fc13d9ed477f4f7769e173ec657d5f3b6f1580f1"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "93b3ae1904d21481fae0fdd141dce7da77c8e500d51db8fde0985566a83bc815"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d371962ba83dcac55d0778bd10bef5f97170d174e7b4ee3a702175af1da9e3ad"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "98c5955659b57af6741535f12254276367abf76321d462c3976dd16ff374551a"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-arm64.tar.gz"
    end
  end

  name "fragua"
  desc "Fragua execution host — run Fragua agents on your own machine"
  homepage "https://fragua.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fragua"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fragua"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next steps:
      fragua login          # store your AgentToken
      fragua agent install  # run the daemon at login (launchd LaunchAgent)
  EOS
end
