# This file was generated by GoReleaser. DO NOT EDIT.
cask "fragua" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "b50ad72805c93326495bd3198c6e43aba8184984bb3f16a5e5cb337ede63175a"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "9e33766966be04088c1e39bac1be5259c7b79153945e431550cdc106bc3444f6"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "abedbe59b794ce16a14a19c5fded7e6467d493ebbe69ae27a24d1e8498ef6dfb"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "72ad69412ed81a5fd7ce035f9e5e19db57af1b563b3d1e04f9d4338b13bf4660"
      url "https://github.com/maquina-app/fragua-tools/releases/download/v#{version}/fragua-linux-arm64.tar.gz"
    end
  end

  name "fragua"
  desc "Fragua execution host — run Fragua agents on your own machine"
  homepage "https://fragua.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fragua"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fragua"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Next steps:
      fragua login          # store your AgentToken
      fragua agent install  # run the daemon at login (launchd LaunchAgent)
  EOS
end
