# This file was generated by GoReleaser. DO NOT EDIT.
cask "recuerd0" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "719d459601f7acb8bc5c818fd24727feb5dedd1abbfebaed57a560b772c8cb9e"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "2fab4a3d3370b88e02cab4f8dcb5fc9038e47bcfff16d7b8b6dce6269268a408"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f2fe2fe548a636bd28005b92438cf9b5fb7c4c77102d01366689fde75d753c64"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "acb9431423b4108703240b7ae0e8fdf23251a3b8f15ae5affc57334ffb46e148"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-arm64.tar.gz"
    end
  end

  name "recuerd0"
  desc "CLI for preserving, versioning, and organizing knowledge from AI conversations"
  homepage "https://recuerd0.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recuerd0"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recuerd0"]
    end
  end

  # No zap stanza required

end
