# This file was generated by GoReleaser. DO NOT EDIT.
cask "recuerd0" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "f40dee4759ff1ffc28d82519036cb0c1606d930e053646151b6b3deed8dfda10"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "166dfa6f30bba5855e9b335f8f092a1ea92d3a4b15825ce16c2e234c4d2e9878"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "41ed6a1e883e04e5c8d801d7508889d87860ffa6b5ce97c547f615c90e2c83cf"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "00906fe8427aadd71ffdf75635bd215557e0d8f0317e5d554141da756387745c"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-arm64.tar.gz"
    end
  end

  name "recuerd0"
  desc "CLI for preserving, versioning, and organizing knowledge from AI conversations"
  homepage "https://recuerd0.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recuerd0"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recuerd0"]
    end
  end

  # No zap stanza required

end
