# This file was generated by GoReleaser. DO NOT EDIT.
cask "recuerd0" do
  version "0.7.1"

  on_macos do
    on_intel do
      sha256 "14c4a1c8b52df5c4889eedd9fdcb1f58b23a3cf8838dc07d410b8b2e07fa1ace"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "4723a8f97c93570746531afece660e2d288910fadc1366f5b05b6a0d4468ad97"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "722e5217053a5ec39cd0fa4903dd5ca96180f7965d1627906a3b0bb9bd10fef5"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "6c883c64e72478c59fce731e22fafe9ed990ae547cbbdce8dd78f2da82d7c147"
      url "https://github.com/maquina-app/recuerd0-cli/releases/download/v#{version}/recuerd0-linux-arm64.tar.gz"
    end
  end

  name "recuerd0"
  desc "CLI for preserving, versioning, and organizing knowledge from AI conversations"
  homepage "https://recuerd0.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recuerd0"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/recuerd0"]
    end
  end

  # No zap stanza required

end
